application: <yourAppServerNameGoesHere>
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: "2.3"

handlers:

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /.*
  script: yaas.app
  secure: optional
